
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages: 
- stage: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build first job
  - job: SecondJob
    steps: 
    - bash: echo Build Second job
- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo  DevDeploy job
- stage: QADeploy
  dependsOn: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo  QADeploy job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo ProdDeploy job

