
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages: 
- stage: Build
  jobs: 
  - job: FirstJob
    steps: 
    - bash: echo Build first job
    - bash: echo $(PipelineLeveLVariable)
    - bash: echo $(Build.BuildNmber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(Build.ArtifactsStagingDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactsStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '$(Build.ArtifactsStagingDirectory)'
    - bash: ls -R $(Build.ArtifactsStagingDirectory)    
#   - stage: DevDeploy
#   variables: 
#     environment : Dev
#   dependsOn: Build
#   jobs: 
#   - job: FirstJob
#     steps: 
#     - bash: echo  $(environment)Deploy job
# - stage: QADeploy
#   variables: 
#     environment : QA
#   dependsOn: Build
#   jobs: 
#   - job: FirstJob
#     steps: 
#     - bash: echo  $(environment)Deploy job
# - stage: ProdDeploy
#   variables: 
#     environment : Prod
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   jobs: 
#   - job: FirstJob
#     steps: 
#     - bash: echo  $(environment)Deploy job

